name: Python Checks

on: [ push, pull_request ]

jobs:
  lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Cache python modules
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.lint.txt') }}

    - name: Install dependencies
      run: |
        make install

    - name: Install Ruff
      run: |
        pip install ruff
    # Update output format to enable automatic inline annotations.
    - name: Run Ruff
      run: |
        ruff check --output-format=github .


    - name: Lint Code (sort requirements)
      run: |
        make lint-requirements

    - name: Lint Code (use f"" style formating)
      run: |
        make lint-stringformat

    # - name: Lint Code (type-check)
    #   run: |
    #     make lint-type-check

    - name: Run tests
      run: |
        make pytest
