name: Python Checks

on:
  push:
    branches:
      - '**'

jobs:
  lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.12']

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Cache python modules
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run Ruff
      run: |
        ruff check --output-format=github .


    - name: Lint Code (sort requirements)
      run: |
        make lint-requirements

    # - name: Lint Code (type-check)
    #   run: |
    #     make lint-type-check

    - name: Run tests
      run: |
        make pytest

    - name: Minimize uv cache
      run: uv cache prune --ci
